module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'scope-enum': [
      2,
      'always',
      [
        'foundation',
        'identity',
        'tenant',
        'user-role',
        'master-data',
        'document',
        'notification',
        'audit',
        'workflow',
        'rules',
        'gst',
        'gstr9',
        'einvoice',
        'ewb',
        'tds',
        'itr',
        'vendor',
        'recon',
        'ap',
        'billing',
        'secretarial',
        'reporting',
        'ui',
        'bff',
        'gateway',
        'infra',
        'ci',
        'ai',
        'deps',
      ],
    ],
  },
};
