import type { ComplianceEvent } from "./types";

function addDays(base: Date, days: number): Date {
  const d = new Date(base);
  d.setDate(d.getDate() + days);
  return d;
}

function monthLabel(base: Date, offset: number): string {
  const d = addDays(base, offset);
  return d.toLocaleString("en-IN", { month: "long" });
}

function yearLabel(base: Date, offset: number): string {
  return addDays(base, offset).getFullYear().toString();
}

function fy(base: Date, offset: number): string {
  const d = addDays(base, offset);
  const y = d.getMonth() >= 3 ? d.getFullYear() : d.getFullYear() - 1;
  return `${y}-${String(y + 1).slice(2)}`;
}

const EVENTS_TEMPLATE: Omit<ComplianceEvent, "id">[] = [
  // ── Indirect Tax (GST) ──────────────────────────────────────────
  {
    title: "GSTR-1 (Monthly)",
    description: "Monthly outward supplies return for invoices issued. Due by 11th of next month.",
    category: "indirect_tax",
    authority: "CBIC",
    sectionRef: "GST § 37",
    formRef: "GSTR-1",
    dueDateOffset: 2,
    penalty: "₹50/day late fee, ₹20/day for nil returns",
    status: "upcoming",
    linkedModule: "/compliance/gst",
  },
  {
    title: "GSTR-1 IFF (QRMP M1)",
    description: "Invoice Furnishing Facility for QRMP filers — Month 1 of the quarter.",
    category: "indirect_tax",
    authority: "CBIC",
    sectionRef: "GST § 37",
    formRef: "GSTR-1 IFF",
    dueDateOffset: 4,
    penalty: "₹50/day late fee",
    status: "upcoming",
    linkedModule: "/compliance/gst",
  },
  {
    title: "GSTR-1 IFF (QRMP M2)",
    description: "Invoice Furnishing Facility for QRMP filers — Month 2 of the quarter.",
    category: "indirect_tax",
    authority: "CBIC",
    sectionRef: "GST § 37",
    formRef: "GSTR-1 IFF",
    dueDateOffset: 34,
    penalty: "₹50/day late fee",
    status: "upcoming",
    linkedModule: "/compliance/gst",
  },
  {
    title: "GSTR-3B (Monthly)",
    description: "Monthly summary return with tax liability and ITC claim. Due by 20th of next month.",
    category: "indirect_tax",
    authority: "CBIC",
    sectionRef: "GST § 39",
    formRef: "GSTR-3B",
    dueDateOffset: 11,
    penalty: "₹50/day late fee + 18% interest on outstanding tax",
    status: "upcoming",
    linkedModule: "/compliance/gst",
  },
  {
    title: "GSTR-3B QRMP (North/East/Central)",
    description: "Quarterly GSTR-3B for QRMP filers in North, East, and Central Indian states. Due 22nd.",
    category: "indirect_tax",
    authority: "CBIC",
    sectionRef: "GST § 39",
    formRef: "GSTR-3B QRMP",
    dueDateOffset: 13,
    penalty: "₹50/day late fee + 18% interest",
    status: "upcoming",
    linkedModule: "/compliance/gst",
  },
  {
    title: "GSTR-3B QRMP (South/West)",
    description: "Quarterly GSTR-3B for QRMP filers in South and West Indian states. Due 24th.",
    category: "indirect_tax",
    authority: "CBIC",
    sectionRef: "GST § 39",
    formRef: "GSTR-3B QRMP",
    dueDateOffset: 15,
    penalty: "₹50/day late fee + 18% interest",
    status: "upcoming",
    linkedModule: "/compliance/gst",
  },
  {
    title: "PMT-06 (QRMP Tax Payment)",
    description: "Monthly tax payment challan for QRMP scheme filers. Due by 25th.",
    category: "indirect_tax",
    authority: "CBIC",
    sectionRef: "GST Rule 61A",
    formRef: "PMT-06",
    dueDateOffset: 16,
    penalty: "18% interest on delayed payment",
    status: "upcoming",
    linkedModule: "/compliance/gst",
  },
  {
    title: "GSTR-7 (TDS under GST)",
    description: "Return for tax deducted at source under GST by specified deductors.",
    category: "indirect_tax",
    authority: "CBIC",
    sectionRef: "GST § 51",
    formRef: "GSTR-7",
    dueDateOffset: 1,
    penalty: "₹200/day late fee (₹100 CGST + ₹100 SGST)",
    status: "upcoming",
    linkedModule: "/compliance/gst",
  },
  {
    title: "GSTR-8 (E-commerce TCS)",
    description: "Return for tax collected at source by e-commerce operators.",
    category: "indirect_tax",
    authority: "CBIC",
    sectionRef: "GST § 52",
    formRef: "GSTR-8",
    dueDateOffset: 1,
    penalty: "₹200/day late fee",
    status: "upcoming",
    linkedModule: "/compliance/gst",
  },
  {
    title: "GSTR-9 (Annual Return)",
    description: "Annual return consolidating all monthly/quarterly returns for the financial year. Mandatory if turnover > ₹2 Cr.",
    category: "indirect_tax",
    authority: "CBIC",
    sectionRef: "GST § 44",
    formRef: "GSTR-9",
    dueDateOffset: -130,
    penalty: "₹200/day (₹100 CGST + ₹100 SGST), max 0.50% of turnover",
    status: "filed",
    linkedModule: "/compliance/gst",
  },
  {
    title: "GSTR-9C (Reconciliation Statement)",
    description: "Self-certified reconciliation statement between audited financials and GSTR-9. Mandatory if turnover > ₹5 Cr.",
    category: "indirect_tax",
    authority: "CBIC",
    sectionRef: "GST § 44",
    formRef: "GSTR-9C",
    dueDateOffset: -130,
    penalty: "₹200/day late fee, max 0.25% of turnover",
    status: "filed",
    linkedModule: "/compliance/gst",
  },
  {
    title: "LUT (RFD-11) Annual",
    description: "Letter of Undertaking for exports without payment of IGST. Must be filed before start of FY.",
    category: "indirect_tax",
    authority: "CBIC",
    sectionRef: "GST § 16(3)(a)",
    formRef: "RFD-11",
    dueDateOffset: -39,
    penalty: "Export without IGST blocked until LUT filed",
    status: "filed",
    linkedModule: "/compliance/gst",
  },

  // filed GSTR-1 from last month
  {
    title: "GSTR-1 (Previous Month)",
    description: "Monthly outward supplies return — already filed for the previous period.",
    category: "indirect_tax",
    authority: "CBIC",
    sectionRef: "GST § 37",
    formRef: "GSTR-1",
    dueDateOffset: -19,
    penalty: "₹50/day late fee",
    status: "filed",
    linkedModule: "/compliance/gst",
  },
  {
    title: "GSTR-3B (Previous Month)",
    description: "Monthly summary return — already filed for the previous period.",
    category: "indirect_tax",
    authority: "CBIC",
    sectionRef: "GST § 39",
    formRef: "GSTR-3B",
    dueDateOffset: -10,
    penalty: "₹50/day late fee + 18% interest",
    status: "filed",
    linkedModule: "/compliance/gst",
  },

  // ── Direct Tax (IT) — ITA 2025 ──────────────────────────────────
  {
    title: "TDS Deposit (Monthly)",
    description: "Monthly deposit of tax deducted at source to the government. Due by 7th of next month.",
    category: "direct_tax",
    authority: "CBDT",
    sectionRef: "ITA 2025 § 392",
    formRef: "Challan 281",
    dueDateOffset: -2,
    penalty: "1.5% per month interest on delayed payment",
    status: "filed",
    linkedModule: "/compliance/tds",
  },
  {
    title: "TDS Deposit (Current Month)",
    description: "Monthly deposit of tax deducted at source. Due by 7th of the following month.",
    category: "direct_tax",
    authority: "CBDT",
    sectionRef: "ITA 2025 § 392",
    formRef: "Challan 281",
    dueDateOffset: 28,
    penalty: "1.5% per month interest on delayed payment",
    status: "upcoming",
    linkedModule: "/compliance/tds",
  },
  {
    title: "Form 138 (Salary TDS — Q4)",
    description: "Quarterly TDS return for salary deductions (was Form 24Q under ITA 1961). Q4 due 31 May.",
    category: "direct_tax",
    authority: "CBDT",
    sectionRef: "ITA 2025 § 392",
    formRef: "Form 138 (was 24Q)",
    dueDateOffset: -8,
    penalty: "₹200/day late fee u/s 234E + penalty u/s 271H",
    status: "filed",
    linkedModule: "/compliance/tds",
  },
  {
    title: "Form 140 (Non-Salary TDS — Q4)",
    description: "Quarterly TDS return for non-salary resident payments (was Form 26Q). Q4 due 31 May.",
    category: "direct_tax",
    authority: "CBDT",
    sectionRef: "ITA 2025 § 392",
    formRef: "Form 140 (was 26Q)",
    dueDateOffset: -8,
    penalty: "₹200/day late fee u/s 234E",
    status: "filed",
    linkedModule: "/compliance/tds",
  },
  {
    title: "Form 144 (Non-Resident TDS — Q4)",
    description: "Quarterly TDS return for non-resident payments (was Form 27Q). Q4 due 31 May.",
    category: "direct_tax",
    authority: "CBDT",
    sectionRef: "ITA 2025 § 392",
    formRef: "Form 144 (was 27Q)",
    dueDateOffset: -8,
    penalty: "₹200/day late fee u/s 234E",
    status: "filed",
    linkedModule: "/compliance/tds",
  },
  {
    title: "Form 138 (Salary TDS — Q1)",
    description: "Quarterly TDS return for salary deductions. Q1 (Apr–Jun) due 31 July.",
    category: "direct_tax",
    authority: "CBDT",
    sectionRef: "ITA 2025 § 392",
    formRef: "Form 138 (was 24Q)",
    dueDateOffset: 83,
    penalty: "₹200/day late fee u/s 234E",
    status: "upcoming",
    linkedModule: "/compliance/tds",
  },
  {
    title: "Form 140 (Non-Salary TDS — Q1)",
    description: "Quarterly TDS return for non-salary resident payments. Q1 (Apr–Jun) due 31 July.",
    category: "direct_tax",
    authority: "CBDT",
    sectionRef: "ITA 2025 § 392",
    formRef: "Form 140 (was 26Q)",
    dueDateOffset: 83,
    penalty: "₹200/day late fee u/s 234E",
    status: "upcoming",
    linkedModule: "/compliance/tds",
  },
  {
    title: "Form 27EQ (TCS — Q4)",
    description: "Quarterly TCS return. Q4 due 15 May.",
    category: "direct_tax",
    authority: "CBDT",
    sectionRef: "ITA 2025 § 406",
    formRef: "Form 27EQ",
    dueDateOffset: -24,
    penalty: "₹200/day late fee u/s 234E",
    status: "filed",
    linkedModule: "/compliance/tds",
  },
  {
    title: "Form 27EQ (TCS — Q1)",
    description: "Quarterly TCS return. Q1 (Apr–Jun) due 15 July.",
    category: "direct_tax",
    authority: "CBDT",
    sectionRef: "ITA 2025 § 406",
    formRef: "Form 27EQ",
    dueDateOffset: 67,
    penalty: "₹200/day late fee u/s 234E",
    status: "upcoming",
    linkedModule: "/compliance/tds",
  },
  {
    title: "Form 130 Issuance (Salary Certificate)",
    description: "Annual salary TDS certificate issued to employees (was Form 16). Due by 15 June.",
    category: "direct_tax",
    authority: "CBDT",
    sectionRef: "ITA 2025 § 394",
    formRef: "Form 130 (was Form 16)",
    dueDateOffset: 37,
    penalty: "₹100/day penalty for delay u/s 272A",
    status: "upcoming",
    linkedModule: "/compliance/tds",
  },
  {
    title: "Form 131 (Non-Salary TDS Certificate — Q4)",
    description: "TDS certificate for non-salary payments (was Form 16A). Due within 15 days of TDS return filing.",
    category: "direct_tax",
    authority: "CBDT",
    sectionRef: "ITA 2025 § 394",
    formRef: "Form 131 (was Form 16A)",
    dueDateOffset: 7,
    penalty: "₹100/day penalty u/s 272A",
    status: "due_soon",
    linkedModule: "/compliance/tds",
  },
  {
    title: "Advance Tax — Installment 1 (15%)",
    description: "First advance tax installment — 15% of estimated tax liability for the year. Due 15 June.",
    category: "direct_tax",
    authority: "CBDT",
    sectionRef: "ITA 2025 § 219",
    formRef: "Challan 280",
    dueDateOffset: 37,
    penalty: "Interest u/s 234C on shortfall",
    status: "upcoming",
    linkedModule: "/compliance/tds",
  },
  {
    title: "Advance Tax — Installment 2 (45%)",
    description: "Second advance tax installment — 45% cumulative of estimated tax. Due 15 September.",
    category: "direct_tax",
    authority: "CBDT",
    sectionRef: "ITA 2025 § 219",
    formRef: "Challan 280",
    dueDateOffset: 129,
    penalty: "Interest u/s 234C on shortfall",
    status: "upcoming",
    linkedModule: "/compliance/itr",
  },
  {
    title: "ITR-1 / ITR-2 / ITR-4 (Non-Audit)",
    description: "Income tax return for individuals, HUFs, and small businesses not subject to audit. Due 31 July.",
    category: "direct_tax",
    authority: "CBDT",
    sectionRef: "ITA 2025 § 263",
    formRef: "ITR-1/2/4",
    dueDateOffset: 83,
    penalty: "₹5,000 late fee u/s 234F (₹1,000 if income ≤ ₹5L)",
    status: "upcoming",
    linkedModule: "/compliance/itr",
  },
  {
    title: "ITR-3 / ITR-5 / ITR-6 (Audit Cases)",
    description: "Income tax return for businesses/companies subject to audit. Due 31 October.",
    category: "direct_tax",
    authority: "CBDT",
    sectionRef: "ITA 2025 § 263",
    formRef: "ITR-3/5/6",
    dueDateOffset: 175,
    penalty: "₹5,000 late fee u/s 234F",
    status: "upcoming",
    linkedModule: "/compliance/itr",
  },
  {
    title: "Tax Audit Report (3CA/3CB-3CD)",
    description: "Tax audit report submission for businesses with turnover exceeding threshold. Due 30 September.",
    category: "direct_tax",
    authority: "CBDT",
    sectionRef: "ITA 2025 § 275",
    formRef: "Form 3CA/3CB-3CD",
    dueDateOffset: 144,
    penalty: "0.5% of turnover or ₹1,50,000 (whichever is lower)",
    status: "upcoming",
    linkedModule: "/compliance/itr",
  },
  {
    title: "194-IA (Property TDS Challan)",
    description: "Challan-cum-statement for TDS on property transfer. Due 30 days from month-end of transaction.",
    category: "direct_tax",
    authority: "CBDT",
    sectionRef: "ITA 2025 § 375",
    formRef: "Form 26QB",
    dueDateOffset: 22,
    penalty: "1.5% per month interest + penalty u/s 271H",
    status: "upcoming",
    linkedModule: "/compliance/tds",
  },

  // ── Statutory (PF / ESI / ROC) ──────────────────────────────────
  {
    title: "PF Contribution (Current Month)",
    description: "Monthly provident fund contribution deposit. 12% of basic + DA. Due by 15th of next month.",
    category: "statutory",
    authority: "EPFO",
    formRef: "ECR",
    dueDateOffset: 6,
    penalty: "Damages @ 5-25% of arrears + interest @ 12% p.a.",
    status: "due_soon",
    linkedModule: "/data-sources/payroll",
  },
  {
    title: "PF Contribution (Previous Month)",
    description: "Monthly provident fund contribution deposit — already remitted for the previous month.",
    category: "statutory",
    authority: "EPFO",
    formRef: "ECR",
    dueDateOffset: -24,
    penalty: "Damages @ 5-25%",
    status: "filed",
    linkedModule: "/data-sources/payroll",
  },
  {
    title: "ESI Contribution (Current Month)",
    description: "Monthly Employee State Insurance contribution. Due by 15th of next month.",
    category: "statutory",
    authority: "ESIC",
    formRef: "ESI Challan",
    dueDateOffset: 6,
    penalty: "12% p.a. interest on delayed payment",
    status: "due_soon",
    linkedModule: "/data-sources/payroll",
  },
  {
    title: "ESI Contribution (Previous Month)",
    description: "Monthly ESI contribution — already remitted for the previous month.",
    category: "statutory",
    authority: "ESIC",
    formRef: "ESI Challan",
    dueDateOffset: -24,
    penalty: "12% p.a. interest",
    status: "filed",
    linkedModule: "/data-sources/payroll",
  },
  {
    title: "LLP Form 11 (Annual Return)",
    description: "Annual return for Limited Liability Partnerships. Due by 30 May each year.",
    category: "statutory",
    authority: "MCA",
    formRef: "LLP Form 11",
    dueDateOffset: -9,
    penalty: "₹100/day late fee",
    status: "filed",
    linkedModule: "/documents",
  },
  {
    title: "MCA AOC-4 (Financial Statements)",
    description: "Filing of financial statements with MCA. Due within 30 days from AGM date.",
    category: "statutory",
    authority: "MCA",
    formRef: "AOC-4",
    dueDateOffset: 53,
    penalty: "₹100/day late fee for company + ₹50/day for directors",
    status: "upcoming",
    linkedModule: "/documents",
  },
  {
    title: "MCA MGT-7 (Annual Return)",
    description: "Company annual return filing with MCA. Due within 60 days from AGM date.",
    category: "statutory",
    authority: "MCA",
    formRef: "MGT-7",
    dueDateOffset: 83,
    penalty: "₹100/day late fee",
    status: "upcoming",
    linkedModule: "/documents",
  },
  {
    title: "PAS-6 (Half-Yearly Reconciliation)",
    description: "Reconciliation of share capital audit with depositories. Due within 60 days from half-year end.",
    category: "statutory",
    authority: "MCA",
    formRef: "PAS-6",
    dueDateOffset: 52,
    penalty: "₹1,000/day, max ₹5,00,000",
    status: "upcoming",
    linkedModule: "/documents",
  },
  {
    title: "DIR-3 KYC (Director KYC)",
    description: "Annual KYC for all directors holding DIN. Due by 30 September.",
    category: "statutory",
    authority: "MCA",
    formRef: "DIR-3 KYC",
    dueDateOffset: 144,
    penalty: "₹5,000 penalty + DIN deactivated",
    status: "upcoming",
    linkedModule: "/documents",
  },

  // ── More past / due-soon events for density ─────────────────────
  {
    title: "GSTR-7 (Previous Month)",
    description: "TDS under GST return — already filed for the previous period.",
    category: "indirect_tax",
    authority: "CBIC",
    sectionRef: "GST § 51",
    formRef: "GSTR-7",
    dueDateOffset: -20,
    penalty: "₹200/day late fee",
    status: "filed",
    linkedModule: "/compliance/gst",
  },
  {
    title: "TDS Deposit (March — Govt)",
    description: "Government deductors — TDS for March deposited on same day (without challan).",
    category: "direct_tax",
    authority: "CBDT",
    sectionRef: "ITA 2025 § 392",
    formRef: "Book Entry",
    dueDateOffset: -39,
    penalty: "1.5% per month interest",
    status: "filed",
    linkedModule: "/compliance/tds",
  },
  {
    title: "PF Annual Return",
    description: "Annual PF return consolidating monthly ECRs. Due by 25 April.",
    category: "statutory",
    authority: "EPFO",
    formRef: "Form 3A/6A",
    dueDateOffset: -14,
    penalty: "Damages up to 100% of arrears",
    status: "filed",
    linkedModule: "/data-sources/payroll",
  },
  {
    title: "GSTR-1 (Next Month)",
    description: "Monthly outward supplies return for the next reporting period.",
    category: "indirect_tax",
    authority: "CBIC",
    sectionRef: "GST § 37",
    formRef: "GSTR-1",
    dueDateOffset: 32,
    penalty: "₹50/day late fee",
    status: "upcoming",
    linkedModule: "/compliance/gst",
  },
  {
    title: "GSTR-3B (Next Month)",
    description: "Monthly summary return for the next reporting period.",
    category: "indirect_tax",
    authority: "CBIC",
    sectionRef: "GST § 39",
    formRef: "GSTR-3B",
    dueDateOffset: 41,
    penalty: "₹50/day late fee + 18% interest",
    status: "upcoming",
    linkedModule: "/compliance/gst",
  },
  {
    title: "PF Contribution (Month +2)",
    description: "Monthly provident fund contribution deposit for the period two months ahead.",
    category: "statutory",
    authority: "EPFO",
    formRef: "ECR",
    dueDateOffset: 36,
    penalty: "Damages @ 5-25%",
    status: "upcoming",
    linkedModule: "/data-sources/payroll",
  },
  {
    title: "ESI Contribution (Month +2)",
    description: "Monthly ESI contribution for the period two months ahead.",
    category: "statutory",
    authority: "ESIC",
    formRef: "ESI Challan",
    dueDateOffset: 36,
    penalty: "12% p.a. interest",
    status: "upcoming",
    linkedModule: "/data-sources/payroll",
  },
  {
    title: "GSTR-8 (Previous Month)",
    description: "E-commerce TCS return — already filed for the previous period.",
    category: "indirect_tax",
    authority: "CBIC",
    sectionRef: "GST § 52",
    formRef: "GSTR-8",
    dueDateOffset: -20,
    penalty: "₹200/day late fee",
    status: "filed",
    linkedModule: "/compliance/gst",
  },
  {
    title: "Advance Tax — Installment 3 (75%)",
    description: "Third advance tax installment — 75% cumulative of estimated tax. Due 15 December.",
    category: "direct_tax",
    authority: "CBDT",
    sectionRef: "ITA 2025 § 219",
    formRef: "Challan 280",
    dueDateOffset: -145,
    penalty: "Interest u/s 234C on shortfall",
    status: "filed",
    linkedModule: "/compliance/itr",
  },
  {
    title: "Advance Tax — Installment 4 (100%)",
    description: "Final advance tax installment — 100% of estimated tax. Due 15 March.",
    category: "direct_tax",
    authority: "CBDT",
    sectionRef: "ITA 2025 § 219",
    formRef: "Challan 280",
    dueDateOffset: -55,
    penalty: "Interest u/s 234B on total shortfall",
    status: "filed",
    linkedModule: "/compliance/itr",
  },
  {
    title: "Form 131 (Non-Salary Certificate — Q1)",
    description: "TDS certificate for non-salary payments. Q1 due within 15 days of Q1 return filing.",
    category: "direct_tax",
    authority: "CBDT",
    sectionRef: "ITA 2025 § 394",
    formRef: "Form 131 (was Form 16A)",
    dueDateOffset: 98,
    penalty: "₹100/day penalty u/s 272A",
    status: "upcoming",
    linkedModule: "/compliance/tds",
  },
  {
    title: "ESI Half-Yearly Return",
    description: "Half-yearly ESI return for the period Oct–Mar. Due by 12 May.",
    category: "statutory",
    authority: "ESIC",
    formRef: "ESI Form 5",
    dueDateOffset: -27,
    penalty: "₹5,000 late fee + damages",
    status: "filed",
    linkedModule: "/data-sources/payroll",
  },
  {
    title: "ITR-7 (Trusts / Institutions)",
    description: "Income tax return for trusts, political parties, and institutions. Due 31 October.",
    category: "direct_tax",
    authority: "CBDT",
    sectionRef: "ITA 2025 § 263",
    formRef: "ITR-7",
    dueDateOffset: 175,
    penalty: "₹5,000 late fee u/s 234F",
    status: "upcoming",
    linkedModule: "/compliance/itr",
  },
];

export function getComplianceEvents(today: Date = new Date()): (ComplianceEvent & { dueDate: Date })[] {
  return EVENTS_TEMPLATE.map((tmpl, i) => ({
    ...tmpl,
    id: `evt-${String(i + 1).padStart(3, "0")}`,
    dueDate: addDays(today, tmpl.dueDateOffset),
  }));
}

export function resolveEventsForMonth(
  events: (ComplianceEvent & { dueDate: Date })[],
  year: number,
  month: number,
): (ComplianceEvent & { dueDate: Date })[] {
  return events.filter((e) => e.dueDate.getFullYear() === year && e.dueDate.getMonth() === month);
}
