import type { EventTemplate } from './calendar.types';

const Q_LABELS: Record<number, string> = {
  0: 'Q3 (Oct–Dec)', 1: 'Q3', 4: 'Q4 (Jan–Mar)', 5: 'Q4',
  6: 'Q1 (Apr–Jun)', 7: 'Q1', 10: 'Q2 (Jul–Sep)', 11: 'Q2',
};

function quarterLabel(d: Date): string {
  const m = d.getMonth();
  if (m >= 3 && m <= 5) return 'Q1 (Apr–Jun)';
  if (m >= 6 && m <= 8) return 'Q2 (Jul–Sep)';
  if (m >= 9 && m <= 11) return 'Q3 (Oct–Dec)';
  return 'Q4 (Jan–Mar)';
}

function fyLabel(d: Date): string {
  const m = d.getMonth();
  const y = m >= 3 ? d.getFullYear() : d.getFullYear() - 1;
  return `FY ${y}-${String(y + 1).slice(2)}`;
}

function tyLabel(d: Date): string {
  const m = d.getMonth();
  const y = m >= 3 ? d.getFullYear() : d.getFullYear() - 1;
  return `TY ${y}-${String(y + 1).slice(2)}`;
}

function monthLabel(d: Date): string {
  return `(${d.toLocaleString('en-IN', { month: 'long' })})`;
}

export const EVENT_TEMPLATES: EventTemplate[] = [
  // ── Indirect Tax (GST) ──────────────────────────────────────────
  {
    eventType: 'gstr1_monthly',
    title: 'GSTR-1',
    description: 'Monthly outward supplies return for invoices issued. Due by 11th of next month.',
    category: 'indirect_tax',
    authority: 'CBIC',
    sectionRef: 'GST § 37',
    formRef: 'GSTR-1',
    penalty: '₹50/day late fee, ₹20/day for nil returns',
    linkedModule: '/compliance/gst',
    schedule: { type: 'monthly', dayOfMonth: 11 },
    filter: (c) => c.filingScheme === 'monthly',
  },
  {
    eventType: 'gstr1_iff_m1',
    title: 'GSTR-1 IFF',
    titleSuffix: (d) => `(QRMP M1 — ${d.toLocaleString('en-IN', { month: 'short' })})`,
    description: 'Invoice Furnishing Facility for QRMP filers — Month 1 of the quarter.',
    category: 'indirect_tax',
    authority: 'CBIC',
    sectionRef: 'GST § 37',
    formRef: 'GSTR-1 IFF',
    penalty: '₹50/day late fee',
    linkedModule: '/compliance/gst',
    schedule: { type: 'quarterly', months: [4, 7, 10, 1], dayOfMonth: 13 },
    filter: (c) => c.filingScheme === 'qrmp',
  },
  {
    eventType: 'gstr1_iff_m2',
    title: 'GSTR-1 IFF',
    titleSuffix: (d) => `(QRMP M2 — ${d.toLocaleString('en-IN', { month: 'short' })})`,
    description: 'Invoice Furnishing Facility for QRMP filers — Month 2 of the quarter.',
    category: 'indirect_tax',
    authority: 'CBIC',
    sectionRef: 'GST § 37',
    formRef: 'GSTR-1 IFF',
    penalty: '₹50/day late fee',
    linkedModule: '/compliance/gst',
    schedule: { type: 'quarterly', months: [5, 8, 11, 2], dayOfMonth: 13 },
    filter: (c) => c.filingScheme === 'qrmp',
  },
  {
    eventType: 'gstr1_qrmp',
    title: 'GSTR-1 Quarterly',
    titleSuffix: (d) => quarterLabel(d),
    description: 'Quarterly outward supplies return for QRMP filers.',
    category: 'indirect_tax',
    authority: 'CBIC',
    sectionRef: 'GST § 37',
    formRef: 'GSTR-1',
    penalty: '₹50/day late fee',
    linkedModule: '/compliance/gst',
    schedule: { type: 'quarterly', months: [6, 9, 0, 3], dayOfMonth: 13 },
    filter: (c) => c.filingScheme === 'qrmp',
  },
  {
    eventType: 'gstr3b_monthly',
    title: 'GSTR-3B',
    description: 'Monthly summary return with tax liability and ITC claim. Due by 20th of next month.',
    category: 'indirect_tax',
    authority: 'CBIC',
    sectionRef: 'GST § 39',
    formRef: 'GSTR-3B',
    penalty: '₹50/day late fee + 18% interest on outstanding tax',
    linkedModule: '/compliance/gst',
    schedule: { type: 'monthly', dayOfMonth: 20 },
    filter: (c) => c.filingScheme === 'monthly',
  },
  {
    eventType: 'gstr3b_qrmp_north',
    title: 'GSTR-3B QRMP (North/East/Central)',
    titleSuffix: (d) => quarterLabel(d),
    description: 'Quarterly GSTR-3B for QRMP filers in North, East, and Central Indian states. Due 22nd.',
    category: 'indirect_tax',
    authority: 'CBIC',
    sectionRef: 'GST § 39',
    formRef: 'GSTR-3B QRMP',
    penalty: '₹50/day late fee + 18% interest',
    linkedModule: '/compliance/gst',
    schedule: { type: 'quarterly', months: [6, 9, 0, 3], dayOfMonth: 22 },
    filter: (c) => c.filingScheme === 'qrmp',
  },
  {
    eventType: 'gstr3b_qrmp_south',
    title: 'GSTR-3B QRMP (South/West)',
    titleSuffix: (d) => quarterLabel(d),
    description: 'Quarterly GSTR-3B for QRMP filers in South and West Indian states. Due 24th.',
    category: 'indirect_tax',
    authority: 'CBIC',
    sectionRef: 'GST § 39',
    formRef: 'GSTR-3B QRMP',
    penalty: '₹50/day late fee + 18% interest',
    linkedModule: '/compliance/gst',
    schedule: { type: 'quarterly', months: [6, 9, 0, 3], dayOfMonth: 24 },
    filter: (c) => c.filingScheme === 'qrmp',
  },
  {
    eventType: 'pmt06',
    title: 'PMT-06 (QRMP Tax Payment)',
    description: 'Monthly tax payment challan for QRMP scheme filers. Due by 25th.',
    category: 'indirect_tax',
    authority: 'CBIC',
    sectionRef: 'GST Rule 61A',
    formRef: 'PMT-06',
    penalty: '18% interest on delayed payment',
    linkedModule: '/compliance/gst',
    schedule: { type: 'monthly', dayOfMonth: 25 },
    filter: (c) => c.filingScheme === 'qrmp',
  },
  {
    eventType: 'gstr7',
    title: 'GSTR-7 (TDS under GST)',
    description: 'Return for tax deducted at source under GST by specified deductors.',
    category: 'indirect_tax',
    authority: 'CBIC',
    sectionRef: 'GST § 51',
    formRef: 'GSTR-7',
    penalty: '₹200/day late fee (₹100 CGST + ₹100 SGST)',
    linkedModule: '/compliance/gst',
    schedule: { type: 'monthly', dayOfMonth: 10 },
  },
  {
    eventType: 'gstr8',
    title: 'GSTR-8 (E-commerce TCS)',
    description: 'Return for tax collected at source by e-commerce operators.',
    category: 'indirect_tax',
    authority: 'CBIC',
    sectionRef: 'GST § 52',
    formRef: 'GSTR-8',
    penalty: '₹200/day late fee',
    linkedModule: '/compliance/gst',
    schedule: { type: 'monthly', dayOfMonth: 10 },
  },
  {
    eventType: 'gstr9',
    title: 'GSTR-9 (Annual Return)',
    titleSuffix: (d) => fyLabel(d),
    description: 'Annual return consolidating all monthly/quarterly returns. Mandatory if turnover > ₹2 Cr.',
    category: 'indirect_tax',
    authority: 'CBIC',
    sectionRef: 'GST § 44',
    formRef: 'GSTR-9',
    penalty: '₹200/day (₹100 CGST + ₹100 SGST), max 0.50% of turnover',
    linkedModule: '/compliance/gst',
    schedule: { type: 'annual', month: 11, dayOfMonth: 31 },
    filter: (c) => c.annualTurnover >= 2_00_00_000,
  },
  {
    eventType: 'gstr9c',
    title: 'GSTR-9C (Reconciliation Statement)',
    titleSuffix: (d) => fyLabel(d),
    description: 'Self-certified reconciliation statement. Mandatory if turnover > ₹5 Cr.',
    category: 'indirect_tax',
    authority: 'CBIC',
    sectionRef: 'GST § 44',
    formRef: 'GSTR-9C',
    penalty: '₹200/day late fee, max 0.25% of turnover',
    linkedModule: '/compliance/gst',
    schedule: { type: 'annual', month: 11, dayOfMonth: 31 },
    filter: (c) => c.annualTurnover >= 5_00_00_000,
  },
  {
    eventType: 'lut_rfd11',
    title: 'LUT (RFD-11) Annual',
    titleSuffix: (d) => fyLabel(d),
    description: 'Letter of Undertaking for exports without payment of IGST. File before start of FY.',
    category: 'indirect_tax',
    authority: 'CBIC',
    sectionRef: 'GST § 16(3)(a)',
    formRef: 'RFD-11',
    penalty: 'Export without IGST blocked until LUT filed',
    linkedModule: '/compliance/gst',
    schedule: { type: 'annual', month: 2, dayOfMonth: 31 },
  },

  // ── Direct Tax (IT) — ITA 2025 ──────────────────────────────────
  {
    eventType: 'tds_deposit',
    title: 'TDS Deposit',
    description: 'Monthly deposit of tax deducted at source to the government. Due by 7th of next month.',
    category: 'direct_tax',
    authority: 'CBDT',
    sectionRef: 'ITA 2025 § 392',
    formRef: 'Challan 281',
    penalty: '1.5% per month interest on delayed payment',
    linkedModule: '/compliance/tds',
    schedule: { type: 'monthly', dayOfMonth: 7 },
  },
  {
    eventType: 'form138',
    title: 'Form 138 (Salary TDS)',
    titleSuffix: (d) => quarterLabel(d),
    description: 'Quarterly TDS return for salary deductions (was Form 24Q under ITA 1961).',
    category: 'direct_tax',
    authority: 'CBDT',
    sectionRef: 'ITA 2025 § 392',
    formRef: 'Form 138 (was 24Q)',
    penalty: '₹200/day late fee u/s 234E + penalty u/s 271H',
    linkedModule: '/compliance/tds',
    schedule: { type: 'quarterly', months: [4, 6, 9, 0], dayOfMonth: 31 },
  },
  {
    eventType: 'form140',
    title: 'Form 140 (Non-Salary TDS)',
    titleSuffix: (d) => quarterLabel(d),
    description: 'Quarterly TDS return for non-salary resident payments (was Form 26Q).',
    category: 'direct_tax',
    authority: 'CBDT',
    sectionRef: 'ITA 2025 § 392',
    formRef: 'Form 140 (was 26Q)',
    penalty: '₹200/day late fee u/s 234E',
    linkedModule: '/compliance/tds',
    schedule: { type: 'quarterly', months: [4, 6, 9, 0], dayOfMonth: 31 },
  },
  {
    eventType: 'form144',
    title: 'Form 144 (Non-Resident TDS)',
    titleSuffix: (d) => quarterLabel(d),
    description: 'Quarterly TDS return for non-resident payments (was Form 27Q).',
    category: 'direct_tax',
    authority: 'CBDT',
    sectionRef: 'ITA 2025 § 392',
    formRef: 'Form 144 (was 27Q)',
    penalty: '₹200/day late fee u/s 234E',
    linkedModule: '/compliance/tds',
    schedule: { type: 'quarterly', months: [4, 6, 9, 0], dayOfMonth: 31 },
  },
  {
    eventType: 'form27eq',
    title: 'Form 27EQ (TCS)',
    titleSuffix: (d) => quarterLabel(d),
    description: 'Quarterly TCS return.',
    category: 'direct_tax',
    authority: 'CBDT',
    sectionRef: 'ITA 2025 § 406',
    formRef: 'Form 27EQ',
    penalty: '₹200/day late fee u/s 234E',
    linkedModule: '/compliance/tds',
    schedule: { type: 'quarterly', months: [4, 6, 9, 0], dayOfMonth: 15 },
  },
  {
    eventType: 'form130',
    title: 'Form 130 (Salary Certificate)',
    titleSuffix: (d) => tyLabel(d),
    description: 'Annual salary TDS certificate issued to employees (was Form 16). Due by 15 June.',
    category: 'direct_tax',
    authority: 'CBDT',
    sectionRef: 'ITA 2025 § 394',
    formRef: 'Form 130 (was Form 16)',
    penalty: '₹100/day penalty for delay u/s 272A',
    linkedModule: '/compliance/tds',
    schedule: { type: 'annual', month: 5, dayOfMonth: 15 },
  },
  {
    eventType: 'form131',
    title: 'Form 131 (Non-Salary Certificate)',
    titleSuffix: (d) => quarterLabel(d),
    description: 'TDS certificate for non-salary payments (was Form 16A). Due within 15 days of TDS return.',
    category: 'direct_tax',
    authority: 'CBDT',
    sectionRef: 'ITA 2025 § 394',
    formRef: 'Form 131 (was Form 16A)',
    penalty: '₹100/day penalty u/s 272A',
    linkedModule: '/compliance/tds',
    schedule: { type: 'quarterly', months: [5, 7, 10, 1], dayOfMonth: 15 },
  },
  {
    eventType: 'advance_tax_q1',
    title: 'Advance Tax — Installment 1 (15%)',
    titleSuffix: (d) => tyLabel(d),
    description: 'First advance tax installment — 15% of estimated tax liability. Due 15 June.',
    category: 'direct_tax',
    authority: 'CBDT',
    sectionRef: 'ITA 2025 § 219',
    formRef: 'Challan 280',
    penalty: 'Interest u/s 234C on shortfall',
    linkedModule: '/compliance/itr',
    schedule: { type: 'annual', month: 5, dayOfMonth: 15 },
  },
  {
    eventType: 'advance_tax_q2',
    title: 'Advance Tax — Installment 2 (45%)',
    titleSuffix: (d) => tyLabel(d),
    description: 'Second advance tax installment — 45% cumulative of estimated tax. Due 15 September.',
    category: 'direct_tax',
    authority: 'CBDT',
    sectionRef: 'ITA 2025 § 219',
    formRef: 'Challan 280',
    penalty: 'Interest u/s 234C on shortfall',
    linkedModule: '/compliance/itr',
    schedule: { type: 'annual', month: 8, dayOfMonth: 15 },
  },
  {
    eventType: 'advance_tax_q3',
    title: 'Advance Tax — Installment 3 (75%)',
    titleSuffix: (d) => tyLabel(d),
    description: 'Third advance tax installment — 75% cumulative of estimated tax. Due 15 December.',
    category: 'direct_tax',
    authority: 'CBDT',
    sectionRef: 'ITA 2025 § 219',
    formRef: 'Challan 280',
    penalty: 'Interest u/s 234C on shortfall',
    linkedModule: '/compliance/itr',
    schedule: { type: 'annual', month: 11, dayOfMonth: 15 },
  },
  {
    eventType: 'advance_tax_q4',
    title: 'Advance Tax — Installment 4 (100%)',
    titleSuffix: (d) => tyLabel(d),
    description: 'Final advance tax installment — 100% of estimated tax. Due 15 March.',
    category: 'direct_tax',
    authority: 'CBDT',
    sectionRef: 'ITA 2025 § 219',
    formRef: 'Challan 280',
    penalty: 'Interest u/s 234B on total shortfall',
    linkedModule: '/compliance/itr',
    schedule: { type: 'annual', month: 2, dayOfMonth: 15 },
  },
  {
    eventType: 'itr_non_audit',
    title: 'ITR-1/2/4 (Non-Audit)',
    titleSuffix: (d) => tyLabel(d),
    description: 'Income tax return for individuals, HUFs, and small businesses not subject to audit. Due 31 July.',
    category: 'direct_tax',
    authority: 'CBDT',
    sectionRef: 'ITA 2025 § 263',
    formRef: 'ITR-1/2/4',
    penalty: '₹5,000 late fee u/s 234F (₹1,000 if income ≤ ₹5L)',
    linkedModule: '/compliance/itr',
    schedule: { type: 'annual', month: 6, dayOfMonth: 31 },
    filter: (c) => !c.requiresAudit,
  },
  {
    eventType: 'itr_audit',
    title: 'ITR-3/5/6 (Audit Cases)',
    titleSuffix: (d) => tyLabel(d),
    description: 'Income tax return for businesses/companies subject to audit. Due 31 October.',
    category: 'direct_tax',
    authority: 'CBDT',
    sectionRef: 'ITA 2025 § 263',
    formRef: 'ITR-3/5/6',
    penalty: '₹5,000 late fee u/s 234F',
    linkedModule: '/compliance/itr',
    schedule: { type: 'annual', month: 9, dayOfMonth: 31 },
    filter: (c) => c.requiresAudit,
  },
  {
    eventType: 'itr7',
    title: 'ITR-7 (Trusts/Institutions)',
    titleSuffix: (d) => tyLabel(d),
    description: 'Income tax return for trusts, political parties, and institutions. Due 31 October.',
    category: 'direct_tax',
    authority: 'CBDT',
    sectionRef: 'ITA 2025 § 263',
    formRef: 'ITR-7',
    penalty: '₹5,000 late fee u/s 234F',
    linkedModule: '/compliance/itr',
    schedule: { type: 'annual', month: 9, dayOfMonth: 31 },
    filter: (c) => c.businessType === 'trust',
  },
  {
    eventType: 'tax_audit',
    title: 'Tax Audit Report (3CA/3CB-3CD)',
    titleSuffix: (d) => tyLabel(d),
    description: 'Tax audit report submission for businesses exceeding turnover threshold. Due 30 September.',
    category: 'direct_tax',
    authority: 'CBDT',
    sectionRef: 'ITA 2025 § 275',
    formRef: 'Form 3CA/3CB-3CD',
    penalty: '0.5% of turnover or ₹1,50,000 (whichever is lower)',
    linkedModule: '/compliance/itr',
    schedule: { type: 'annual', month: 8, dayOfMonth: 30 },
    filter: (c) => c.requiresAudit,
  },
  {
    eventType: 'property_tds_194ia',
    title: '194-IA (Property TDS Challan)',
    description: 'Challan-cum-statement for TDS on property transfer. Due 30 days from month-end of transaction.',
    category: 'direct_tax',
    authority: 'CBDT',
    sectionRef: 'ITA 2025 § 375',
    formRef: 'Form 26QB',
    penalty: '1.5% per month interest + penalty u/s 271H',
    linkedModule: '/compliance/tds',
    schedule: { type: 'monthly', dayOfMonth: 30 },
  },

  // ── Statutory (PF / ESI / ROC) ──────────────────────────────────
  {
    eventType: 'pf_monthly',
    title: 'PF Contribution',
    description: 'Monthly provident fund contribution deposit. 12% of basic + DA. Due by 15th of next month.',
    category: 'statutory',
    authority: 'EPFO',
    formRef: 'ECR',
    penalty: 'Damages @ 5-25% of arrears + interest @ 12% p.a.',
    linkedModule: '/data-sources/payroll',
    schedule: { type: 'monthly', dayOfMonth: 15 },
  },
  {
    eventType: 'esi_monthly',
    title: 'ESI Contribution',
    description: 'Monthly Employee State Insurance contribution. Due by 15th of next month.',
    category: 'statutory',
    authority: 'ESIC',
    formRef: 'ESI Challan',
    penalty: '12% p.a. interest on delayed payment',
    linkedModule: '/data-sources/payroll',
    schedule: { type: 'monthly', dayOfMonth: 15 },
  },
  {
    eventType: 'llp_form11',
    title: 'LLP Form 11 (Annual Return)',
    titleSuffix: (d) => fyLabel(d),
    description: 'Annual return for Limited Liability Partnerships. Due by 30 May each year.',
    category: 'statutory',
    authority: 'MCA',
    formRef: 'LLP Form 11',
    penalty: '₹100/day late fee',
    linkedModule: '/documents',
    schedule: { type: 'annual', month: 4, dayOfMonth: 30 },
    filter: (c) => c.businessType === 'llp',
  },
  {
    eventType: 'aoc4',
    title: 'MCA AOC-4 (Financial Statements)',
    titleSuffix: (d) => fyLabel(d),
    description: 'Filing of financial statements with MCA. Due within 30 days from AGM date.',
    category: 'statutory',
    authority: 'MCA',
    formRef: 'AOC-4',
    penalty: '₹100/day late fee for company + ₹50/day for directors',
    linkedModule: '/documents',
    schedule: { type: 'annual', month: 9, dayOfMonth: 30 },
    filter: (c) => c.businessType === 'company',
  },
  {
    eventType: 'mgt7',
    title: 'MCA MGT-7 (Annual Return)',
    titleSuffix: (d) => fyLabel(d),
    description: 'Company annual return filing with MCA. Due within 60 days from AGM date.',
    category: 'statutory',
    authority: 'MCA',
    formRef: 'MGT-7',
    penalty: '₹100/day late fee',
    linkedModule: '/documents',
    schedule: { type: 'annual', month: 10, dayOfMonth: 29 },
    filter: (c) => c.businessType === 'company',
  },
  {
    eventType: 'pas6',
    title: 'PAS-6 (Half-Yearly Reconciliation)',
    titleSuffix: (d) => {
      const m = d.getMonth();
      return m <= 5 ? '(H2)' : '(H1)';
    },
    description: 'Reconciliation of share capital audit with depositories. Due within 60 days from half-year end.',
    category: 'statutory',
    authority: 'MCA',
    formRef: 'PAS-6',
    penalty: '₹1,000/day, max ₹5,00,000',
    linkedModule: '/documents',
    schedule: { type: 'half_yearly', months: [4, 10], dayOfMonth: 29 },
    filter: (c) => c.businessType === 'company',
  },
  {
    eventType: 'dir3_kyc',
    title: 'DIR-3 KYC (Director KYC)',
    titleSuffix: (d) => `(${d.getFullYear()})`,
    description: 'Annual KYC for all directors holding DIN. Due by 30 September.',
    category: 'statutory',
    authority: 'MCA',
    formRef: 'DIR-3 KYC',
    penalty: '₹5,000 penalty + DIN deactivated',
    linkedModule: '/documents',
    schedule: { type: 'annual', month: 8, dayOfMonth: 30 },
    filter: (c) => c.businessType === 'company' || c.businessType === 'llp',
  },
  {
    eventType: 'pf_annual',
    title: 'PF Annual Return',
    titleSuffix: (d) => fyLabel(d),
    description: 'Annual PF return consolidating monthly ECRs. Due by 25 April.',
    category: 'statutory',
    authority: 'EPFO',
    formRef: 'Form 3A/6A',
    penalty: 'Damages up to 100% of arrears',
    linkedModule: '/data-sources/payroll',
    schedule: { type: 'annual', month: 3, dayOfMonth: 25 },
  },
  {
    eventType: 'esi_half_yearly',
    title: 'ESI Half-Yearly Return',
    titleSuffix: (d) => {
      const m = d.getMonth();
      return m <= 5 ? '(Oct–Mar)' : '(Apr–Sep)';
    },
    description: 'Half-yearly ESI return.',
    category: 'statutory',
    authority: 'ESIC',
    formRef: 'ESI Form 5',
    penalty: '₹5,000 late fee + damages',
    linkedModule: '/data-sources/payroll',
    schedule: { type: 'half_yearly', months: [4, 10], dayOfMonth: 12 },
  },
];
